import type { Metadata } from "next";
import Link from "next/link";
import { Users, DollarSign, TrendingUp, Share2, ArrowRight, CheckCircle2, Zap, Globe, BarChart2 } from "lucide-react";
import CTA from "@/components/CTA";

export const metadata: Metadata = {
  title: "Affiliate Program",
  description:
    "Join TradeVault Pro's affiliate program and earn up to 50% revenue share. High commissions, real-time tracking, and fast payouts.",
};

const tiers = [
  {
    name: "Partner",
    referrals: "1–10 clients",
    commission: "25%",
    cpa: "$150",
    color: "from-slate-600 to-slate-700",
    perks: ["Real-time dashboard", "Marketing materials", "Monthly payouts", "Dedicated support"],
  },
  {
    name: "Pro Partner",
    referrals: "11–50 clients",
    commission: "35%",
    cpa: "$250",
    color: "from-indigo-600 to-violet-700",
    perks: ["All Partner perks", "Weekly payouts", "Co-branded pages", "Priority support"],
    popular: true,
  },
  {
    name: "Master Partner",
    referrals: "51+ clients",
    commission: "50%",
    cpa: "$400",
    color: "from-yellow-600 to-orange-600",
    perks: ["All Pro perks", "Daily payouts", "Custom rates", "Dedicated manager"],
  },
];

const benefits = [
  { icon: DollarSign, title: "Up to 50% Revenue Share", desc: "Earn a percentage of all trading revenue generated by your referrals — for life." },
  { icon: BarChart2, title: "Real-time Analytics", desc: "Track clicks, signups, deposits, and commissions with our live affiliate dashboard." },
  { icon: Zap, title: "Fast Payouts", desc: "Get paid weekly or daily (Master Partners). Choose from bank wire, crypto, or PayPal." },
  { icon: Globe, title: "Global Reach", desc: "Marketing materials in 25+ languages. Promote to any audience worldwide." },
  { icon: Share2, title: "Marketing Tools", desc: "Banners, landing pages, email templates, and tracking links — all provided free." },
  { icon: Users, title: "Sub-Affiliate Model", desc: "Recruit other affiliates and earn a % of their commissions too." },
];

const steps = [
  { step: "01", title: "Apply & Get Approved", desc: "Fill out our simple application. Most approvals are within 24 hours." },
  { step: "02", title: "Get Your Links", desc: "Access unique tracking links, banners, and marketing materials instantly." },
  { step: "03", title: "Promote & Refer", desc: "Share your link on your website, social media, YouTube, or email list." },
  { step: "04", title: "Earn Commissions", desc: "Earn revenue share for every deposit your referrals make. Withdraw anytime." },
];

const stats = [
  { value: "8,500+", label: "Active Affiliates" },
  { value: "$4.2M", label: "Paid Out Monthly" },
  { value: "50%", label: "Max Commission" },
  { value: "25+", label: "Languages Supported" },
];

const faqs = [
  { q: "Who can join the affiliate program?", a: "Anyone — bloggers, YouTubers, financial advisors, forex signal providers, and trading educators. We review all applications." },
  { q: "When do I get paid?", a: "Partner tier: monthly. Pro Partner: weekly. Master Partner: daily. Minimum payout is $50." },
  { q: "How long does cookie tracking last?", a: "Our affiliate cookie lasts 90 days, so if someone clicks your link and signs up within 90 days, you earn the commission." },
  { q: "Can I promote to international audiences?", a: "Yes! We operate in 180+ countries with materials in 25 languages." },
];

export default function AffiliatePage() {
  return (
    <div className="overflow-x-hidden">
      {/* Hero */}
      <section className="relative py-24 grid-pattern overflow-hidden">
        <div className="absolute top-1/2 left-1/4 w-96 h-96 bg-yellow-600/8 rounded-full blur-3xl pointer-events-none" />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative">
          <div className="inline-flex items-center gap-2 glass px-4 py-1.5 rounded-full text-xs text-white/60 mb-6">
            <DollarSign className="w-3.5 h-3.5 text-yellow-400" />
            Earn up to 50% commission
          </div>
          <h1 className="text-5xl sm:text-7xl font-extrabold text-white mb-6 tracking-tight">
            Turn your audience into <span className="text-green-600-gold">income</span>
          </h1>
          <p className="text-white/50 text-xl max-w-2xl mx-auto mb-10">
            Join 8,500+ affiliates earning serious money by referring traders to TradeVault Pro.
            Up to 50% revenue share, for the lifetime of every client you refer.
          </p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-2xl mx-auto mb-10">
            {stats.map((s) => (
              <div key={s.label} className="glass-card p-3 text-center">
                <div className="text-2xl font-bold text-green-600-gold">{s.value}</div>
                <div className="text-white/40 text-xs">{s.label}</div>
              </div>
            ))}
          </div>
          <Link href="/contact" className="inline-flex items-center gap-2 px-8 py-4 rounded-xl green-600-gold text-white font-bold glow hover:opacity-90 transition-opacity">
            Apply Now — It's Free <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>

      {/* Commission Tiers */}
      <section className="py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-white mb-4">Commission <span className="text-green-600">Tiers</span></h2>
            <p className="text-white/50">More referrals = higher commissions. Grow with us.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {tiers.map((tier) => (
              <div
                key={tier.name}
                className={`glass-card overflow-hidden ${tier.popular ? "ring-2 ring-indigo-500 glow" : ""}`}
              >
                {tier.popular && (
                  <div className="green-600-brand text-white text-xs font-bold py-1.5 text-center">Most Chosen</div>
                )}
                <div className="p-6">
                  <div className={`w-10 h-10 rounded-xl bg-green-600-to-br ${tier.color} flex items-center justify-center mb-4`}>
                    <Users className="w-5 h-5 text-white" />
                  </div>
                  <h3 className="text-white font-bold text-xl mb-1">{tier.name}</h3>
                  <p className="text-white/40 text-sm mb-4">{tier.referrals} referred</p>
                  <div className="flex items-end gap-3 mb-4 pb-4 border-b border-white/8">
                    <div>
                      <div className="text-white/40 text-xs">Revenue Share</div>
                      <div className="text-4xl font-extrabold text-green-600">{tier.commission}</div>
                    </div>
                    <div>
                      <div className="text-white/40 text-xs">CPA Option</div>
                      <div className="text-2xl font-bold text-white">{tier.cpa}</div>
                    </div>
                  </div>
                  <ul className="space-y-2.5 mb-6">
                    {tier.perks.map((p) => (
                      <li key={p} className="flex items-center gap-2 text-sm text-white/60">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0" />
                        {p}
                      </li>
                    ))}
                  </ul>
                  <Link href="/contact" className={`block text-center py-2.5 rounded-lg text-sm font-semibold transition-all ${tier.popular ? "green-600-brand text-white glow-sm hover:opacity-90" : "border border-white/20 text-white/70 hover:bg-white/5"}`}>
                    Start as {tier.name}
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits */}
      <section className="py-24 bg-black/20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-white mb-4">Why affiliate with <span className="text-green-600">TradeVault Pro</span>?</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {benefits.map((b) => (
              <div key={b.title} className="glass-card p-5 hover:bg-white/8 transition-all">
                <div className="w-10 h-10 rounded-xl bg-indigo-400/10 flex items-center justify-center mb-3">
                  <b.icon className="w-5 h-5 text-indigo-400" />
                </div>
                <h3 className="text-white font-semibold mb-1">{b.title}</h3>
                <p className="text-white/40 text-sm leading-relaxed">{b.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold text-white mb-4">How it <span className="text-green-600">works</span></h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            {steps.map((step, i) => (
              <div key={step.step} className="relative">
                {i < steps.length - 1 && (
                  <div className="hidden md:block absolute top-5 left-full w-full h-px bg-green-600-to-r from-indigo-500/50 to-transparent z-0" />
                )}
                <div className="glass-card p-5 text-center relative">
                  <div className="w-10 h-10 rounded-full green-600-brand text-white text-lg font-bold flex items-center justify-center mx-auto mb-3 glow-sm">
                    {step.step}
                  </div>
                  <h3 className="text-white font-semibold text-sm mb-2">{step.title}</h3>
                  <p className="text-white/40 text-xs leading-relaxed">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-16 bg-black/20">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-white mb-8 text-center">Affiliate <span className="text-green-600">FAQs</span></h2>
          <div className="space-y-4">
            {faqs.map((faq) => (
              <div key={faq.q} className="glass-card p-5">
                <h3 className="text-white font-semibold mb-2">{faq.q}</h3>
                <p className="text-white/50 text-sm leading-relaxed">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-4xl font-bold text-white mb-4">Ready to <span className="text-green-600">start earning?</span></h2>
          <p className="text-white/50 mb-8">Apply in minutes. Free forever. Start earning commissions today.</p>
          <Link href="/contact" className="inline-flex items-center gap-2 px-8 py-4 rounded-xl green-600-brand text-white font-semibold glow hover:opacity-90 transition-opacity">
            Apply for Affiliate Program <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>
          <CTA />
    </div>
  );
}
